// utils/emoji_storage.dart
class EmojiStorage {
  // 📦 ອີໂມຈິທັງໝົດ - 200+ ອັນ
  static const List<Map<String, String>> allEmojis = [
    // ===== ໃບໜ້າ ແລະ ອາລົມ =====
    {'emoji': '❤️', 'label': 'ຮັກ'},
    {'emoji': '😆', 'label': 'ຫົວຂວัน'},
    {'emoji': '🤩', 'label': 'ຕື່ນເຕັ້ນ'},
    {'emoji': '🍻', 'label': 'ຍົກຈອກ'},
    {'emoji': '😊', 'label': 'ຍິ້ມ'},
    {'emoji': '😃', 'label': 'ຍิ້ມກວ້າງ'},
    {'emoji': '😄', 'label': 'ຍິ້ມມີຄວາມສຸກ'},
    {'emoji': '😁', 'label': 'ຍິ້ມເຫັນແຂ້ວ'},
    {'emoji': '😂', 'label': 'ຫົວຈົນນ້ຳຕາໄຫຼ'},
    {'emoji': '🤣', 'label': 'ຫົວກິ້ງ'},
    {'emoji': '😅', 'label': 'ຍິ້ມເື່ອອອກ'},
    {'emoji': '😉', 'label': 'ຢິບຕາ'},
    {'emoji': '😌', 'label': 'ໂລ່ງໃຈ'},
    {'emoji': '😍', 'label': 'ຮັກ'},
    {'emoji': '🥰', 'label': 'ຮັກຫຼາຍ'},
    {'emoji': '😘', 'label': 'ຈູບ'},
    {'emoji': '😗', 'label': 'ຈູບເບົາໆ'},
    {'emoji': '😙', 'label': 'ຈູບຍິ້ມ'},
    {'emoji': '😚', 'label': 'ຈູບຫຼັບຕา'},
    {'emoji': '🥲', 'label': 'ຍິ້ມທັງນ້ຳຕາ'},
    {'emoji': '😜', 'label': 'ຢິบຕາແລບລິ້ນ'},
    {'emoji': '😝', 'label': 'ແລບລິ້ນ'},
    {'emoji': '😛', 'label': 'ແລบລິ້ນ'},
    {'emoji': '🤑', 'label': 'ເງິນ'},
    {'emoji': '🤓', 'label': 'ເນີດ'},
    {'emoji': '😎', 'label': 'ເທ້'},
    {'emoji': '🥸', 'label': 'ປອມຕົວ'},
    {'emoji': '🧐', 'label': 'ກວດສອບ'},
    {'emoji': '🤨', 'label': 'ສົງໄສ'},
    {'emoji': '🧐', 'label': 'ເບິ່ງ'},
    {'emoji': '🤔', 'label': 'ຄິດ'},
    {'emoji': '🤫', 'label': 'ງຽບ'},
    {'emoji': '🤭', 'label': 'ອັດປາກ'},
    {'emoji': '🥺', 'label': 'ອ້ອນວອນ'},
    {'emoji': '🥹', 'label': 'ນ້ຳຕາຊິໄຫຼ'},
    {'emoji': '😢', 'label': 'ເສຍໃຈ'},
    {'emoji': '😭', 'label': 'ໄຫ້'},
    {'emoji': '😤', 'label': 'ຫງຸດຫງິດ'},
    {'emoji': '😠', 'label': 'ຄຽດ'},
    {'emoji': '😡', 'label': 'ໂມໂຫ'},
    {'emoji': '🤬', 'label': 'ຄຽດຫຼາຍ'},
    {'emoji': '😳', 'label': 'ອາຍ'},
    {'emoji': '🥵', 'label': 'ຮ້ອນ'},
    {'emoji': '🥶', 'label': 'ໜາວ'},
    {'emoji': '😱', 'label': 'ຕົກໃຈ'},
    {'emoji': '😨', 'label': 'ຢ້ານ'},
    {'emoji': '😰', 'label': 'ກັງວົນ'},
    {'emoji': '😥', 'label': 'ເສยໃຈ'},
    {'emoji': '😓', 'label': 'ເມື່ອຍ'},
    {'emoji': '🤗', 'label': 'ກອດ'},
    {'emoji': '🤯', 'label': 'ຫົວລະເບີດ'},
    {'emoji': '🥳', 'label': 'ປາຕີ້'},
    {'emoji': '🥴', 'label': 'ມຶນ'},
    {'emoji': '😵', 'label': 'ວິນຫົວ'},
    {'emoji': '😵‍💫', 'label': 'ຫົວໝູນ'},
    {'emoji': '🤒', 'label': 'ປ່ວຍ'},
    {'emoji': '🤕', 'label': 'ເຈັບ'},
    {'emoji': '🤢', 'label': 'ຄື້ນໄສ້'},
    {'emoji': '🤮', 'label': 'ຮາກ'},
    {'emoji': '🤧', 'label': 'ຈາມ'},
    {'emoji': '😷', 'label': 'ຜ້າອັດປາກ'},
    {'emoji': '🤠', 'label': 'ຄາວບອຍ'},
    {'emoji': '🤡', 'label': 'ຕົວຕະຫຼົກ'},
    {'emoji': '👻', 'label': 'ຜີ'},
    {'emoji': '💀', 'label': 'ຫວກະໂຫຼກ'},
    {'emoji': '☠️', 'label': 'ກະໂຫຼກໄຂວ່'},
    {'emoji': '👽', 'label': 'ມະນຸດຕ່າງດາວ'},
    {'emoji': '👾', 'label': 'ເກມ'},
    {'emoji': '🤖', 'label': 'ຫຸ່ນຍົນ'},
    {'emoji': '🎃', 'label': 'ໝາກອຶ'},

    // ===== ສັດ =====
    {'emoji': '🐶', 'label': 'ໝາ'},
    {'emoji': '🐱', 'label': 'ແມວ'},
    {'emoji': '🐭', 'label': 'ໜູ'},
    {'emoji': '🐹', 'label': 'ໜູແຮມສະເຕີ'},
    {'emoji': '🐰', 'label': 'ກະຕ່າຍ'},
    {'emoji': '🦊', 'label': 'ໝາຈິ້ງຈອກ'},
    {'emoji': '🐻', 'label': 'ໝີ'},
    {'emoji': '🐼', 'label': 'ແພਨດ້າ'},
    {'emoji': '🐨', 'label': 'ໂຄອາລາ'},
    {'emoji': '🐯', 'label': 'ເສືອ'},
    {'emoji': '🦁', 'label': 'ສິງໂຕ'},
    {'emoji': '🐮', 'label': 'ງົວ'},
    {'emoji': '🐷', 'label': 'ໝູ'},
    {'emoji': '🐸', 'label': 'ກົບ'},
    {'emoji': '🐵', 'label': 'ລີງ'},
    {'emoji': '🐔', 'label': 'ໄກ່'},
    {'emoji': '🐧', 'label': 'ເພນກວິນ'},
    {'emoji': '🐦', 'label': 'ນົກ'},
    {'emoji': '🦅', 'label': 'ນົກອິນຊີ'},
    {'emoji': '🦉', 'label': 'ນົกເຄົ້າ'},
    {'emoji': '🦇', 'label': 'ເຈຍ'},
    {'emoji': '🐺', 'label': 'ໝາປ່າ'},
    {'emoji': '🐗', 'label': 'ໝູປ່າ'},
    {'emoji': '🐴', 'label': 'ມ້າ'},
    {'emoji': '🦄', 'label': 'ຢູນິຄອນ'},
    {'emoji': '🐝', 'label': 'ເຜິ້ງ'},
    {'emoji': '🐛', 'label': 'ໜອນ'},
    {'emoji': '🦋', 'label': 'ແມງກະເບື້ອ'},
    {'emoji': '🐌', 'label': 'ຫອຍທາກ'},
    {'emoji': '🐞', 'label': 'ແມງໄມ້'},
    {'emoji': '🐜', 'label': 'ມົດ'},
    {'emoji': '🦟', 'label': 'ຍຸງ'},
    {'emoji': '🦗', 'label': 'ຕັກແຕນ'},
    {'emoji': '🪰', 'label': 'ແມງວັນ'},
    {'emoji': '🪱', 'label': 'ຂີ້ເດືອນ'},
    {'emoji': '🐢', 'label': 'ເຕົ່າ'},
    {'emoji': '🐍', 'label': 'ງູ'},
    {'emoji': '🦎', 'label': 'ກະປອມ'},
    {'emoji': '🐊', 'label': 'ແຂ້'},
    {'emoji': '🦖', 'label': 'ໄດໂນເສົາ'},
    {'emoji': '🦕', 'label': 'ໄไดໂနເສົາ'},
    {'emoji': '🐳', 'label': 'ປາວານ'},
    {'emoji': '🐋', 'label': 'ປາວານ'},
    {'emoji': '🐬', 'label': 'ປາໂລມາ'},
    {'emoji': '🦭', 'label': 'ແມວນ້ຳ'},
    {'emoji': '🐟', 'label': 'ປາ'},
    {'emoji': '🐠', 'label': 'ປາເຂດຮ້ອນ'},
    {'emoji': '🐡', 'label': 'ປาປັກເປົ້າ'},
    {'emoji': '🦈', 'label': 'ປາສະຫຼາມ'},
    {'emoji': '🐙', 'label': 'ປາໝຶກ'},
    {'emoji': '🐚', 'label': 'ຫອຍ'},

    // ===== ອາຫານ =====
    {'emoji': '🍎', 'label': 'ໝາກແອບເປີ້ນ'},
    {'emoji': '🍐', 'label': 'ໝາກແພຣ໌'},
    {'emoji': '🍊', 'label': 'ໝາກກ້ຽງ'},
    {'emoji': '🍋', 'label': 'ໝາກນາວ'},
    {'emoji': '🍌', 'label': 'ໝາກກ້ວຍ'},
    {'emoji': '🍉', 'label': 'ໝากໂມ'},
    {'emoji': '🍇', 'label': 'ໝາກອະງຸ່ນ'},
    {'emoji': '🍓', 'label': 'ໝາກສະຕໍເບີຣີ'},
    {'emoji': '🫐', 'label': 'ໝາກບລູເບີຣี'},
    {'emoji': '🍈', 'label': 'ໝາກແຕງ'},
    {'emoji': '🍒', 'label': 'ໝາກເຊີຣີ'},
    {'emoji': '🍑', 'label': 'ໝາກພີຊ'},
    {'emoji': '🥭', 'label': 'ໝາກມ່ວງ'},
    {'emoji': '🍍', 'label': 'ໝາກນັດ'},
    {'emoji': '🥥', 'label': 'ໝາກພ້າວ'},
    {'emoji': '🥝', 'label': 'ໝາກກີວີ'},
    {'emoji': '🍅', 'label': 'ໝາກເລັ່ນ'},
    {'emoji': '🍆', 'label': 'ໝາກເຂືອ'},
    {'emoji': '🥑', 'label': 'ອາໂວຄາໂດ'},
    {'emoji': '🌶️', 'label': 'ໝາກເຜັດ'},
    {'emoji': '🥕', 'label': 'ແຄລອດ'},
    {'emoji': '🌽', 'label': 'ໝາກສາລີ'},
    {'emoji': '🥦', 'label': 'ບຣັອກໂคລີ'},
    {'emoji': '🥬', 'label': 'ຜັກກາດ'},
    {'emoji': '🧄', 'label': 'ກະທຽມ'},
    {'emoji': '🧅', 'label': 'ຫົວຜັກບົ່ວ'},
    {'emoji': '🍄', 'label': 'ເຫັດ'},
    {'emoji': '🥜', 'label': 'ຖົ່ວ'},
    {'emoji': '🌰', 'label': 'ໝາກກໍ່'},
    {'emoji': '🍞', 'label': 'ເຂົ້າຈີ່'},
    {'emoji': '🥐', 'label': 'ຄົວຊອງ'},
    {'emoji': '🥖', 'label': 'ເຂົ້າຈີ່ຝຣັ່ງ'},
    {'emoji': '🧇', 'label': 'ວາເຟິລ'},
    {'emoji': '🥞', 'label': 'ແພນເຄັກ'},
    {'emoji': '🧀', 'label': 'ຊີສ'},
    {'emoji': '🍖', 'label': 'ຊີ້ນ'},
    {'emoji': '🍗', 'label': 'ນ່ອງໄກ່'},
    {'emoji': '🥩', 'label': 'ຊີ້ນສະເຕັກ'},
    {'emoji': '🥓', 'label': 'ເບຄອນ'},
    {'emoji': '🍔', 'label': 'ເບີເກີ'},
    {'emoji': '🍟', 'label': 'ມັນຝຣັ່ງທອດ'},
    {'emoji': '🍕', 'label': 'ພິຊຊ່າ'},
    {'emoji': '🌭', 'label': 'ຮັອດດັອກ'},
    {'emoji': '🥪', 'label': 'ແຊนວິດ'},
    {'emoji': '🥙', 'label': 'ເຄບັບ'},
    {'emoji': '🧆', 'label': 'ຟາລາເຟລ'},
    {'emoji': '🥗', 'label': 'ສະຫຼັດ'},
    {'emoji': '🍲', 'label': 'ຊຸບ'},
    {'emoji': '🥣', 'label': 'ຖ້ວຍ'},
    {'emoji': '🍜', 'label': 'ເຝີ'},
    {'emoji': '🍝', 'label': 'ພາສຕ້າ'},
    {'emoji': '🍛', 'label': 'ແກງ'},
    {'emoji': '🍣', 'label': 'ຊູຊິ'},
    {'emoji': '🍤', 'label': 'ເທມປຸລະ'},
    {'emoji': '🍥', 'label': 'ລູກຊີ້ນປາຢີ່ປຸ່ນ'},
    {'emoji': '🥮', 'label': 'ເຂົ້າໜົມໄຫວ້ພະຈັນ'},
    {'emoji': '🍡', 'label': 'ດັງໂງະ'},
    {'emoji': '🥟', 'label': 'ກ້ຽວ'},
    {'emoji': '🥠', 'label': 'ເຂົ້າໜົມສ່ຽງທາຍ'},
    {'emoji': '🥡', 'label': 'ກ່ອງເຂົ້າ'},
    {'emoji': '🍦', 'label': 'ກະແລັມ'},
    {'emoji': '🍧', 'label': 'ນ້ຳແຂງໄສ'},
    {'emoji': '🍨', 'label': 'ກະແລັມ'},
    {'emoji': '🍩', 'label': 'ໂດນັດ'},
    {'emoji': '🍪', 'label': 'ຄຸກກີ້'},
    {'emoji': '🎂', 'label': 'ເຄັກ'},
    {'emoji': '🍰', 'label': 'ເຄັກ'},
    {'emoji': '🧁', 'label': 'ຄັບເຄັກ'},
    {'emoji': '🥧', 'label': 'ພາຍ'},
    {'emoji': '🍫', 'label': 'ຊັອກໂກແລັດ'},
    {'emoji': '🍬', 'label': 'ລູກອົມ'},
    {'emoji': '🍭', 'label': 'ອົມຍິ້ມ'},
    {'emoji': '🍮', 'label': 'ພຸດດິ້ງ'},
    {'emoji': '🍯', 'label': 'ນ້ຳເຜິ້ງ'},
    {'emoji': '☕', 'label': 'ກາເຟ'},
    {'emoji': '🍵', 'label': 'ຊາ'},
    {'emoji': '🧃', 'label': 'ນ້ຳໝາກໄມ້'},
    {'emoji': '🥤', 'label': 'เครื่องดื่ม'},
    {'emoji': '🧋', 'label': 'ຊາ'},
    {'emoji': '🍺', 'label': 'ເບຍ'},
    {'emoji': '🥂', 'label': 'ແຊມເປນ'},
    {'emoji': '🍷', 'label': 'ວາຍ'},
    {'emoji': '🥃', 'label': 'ວິດສະກີ້'},
    {'emoji': '🍸', 'label': 'ຄັອກເທລ'},
    {'emoji': '🍹', 'label': 'ເຄື່ອງດື່ມ'},
    {'emoji': '🍾', 'label': 'ແຊມເປນ'},

    // ===== ອື່ນໆ =====
    {'emoji': '🧡', 'label': 'ຮັກສີສົ້ມ'},
    {'emoji': '💛', 'label': 'ຮັກສີເຫຼືອງ'},
    {'emoji': '💚', 'label': 'ຮັກสີຂຽວ'},
    {'emoji': '💙', 'label': 'ຮັກສີຟ້າ'},
    {'emoji': '💜', 'label': 'ฮັກສີມ່ວງ'},
    {'emoji': '🖤', 'label': 'ຮັກສີດຳ'},
    {'emoji': '🤍', 'label': 'ຮັກສີຂາວ'},
    {'emoji': '🤎', 'label': 'ຮັກສີນ້ຳຕານ'},
    {'emoji': '💔', 'label': 'ອົກຫັກ'},
    {'emoji': '💝', 'label': 'ຫົວໃຈ'},
    {'emoji': '💖', 'label': 'ຫົວໃຈ'},
    {'emoji': '✨', 'label': 'ວິ້ງ'},
    {'emoji': '⭐', 'label': 'ດາວ'},
    {'emoji': '🌟', 'label': 'ໂດດເດັ່ນ'},
    {'emoji': '💫', 'label': 'ໝູນ'},
    {'emoji': '🔥', 'label': 'ຮ້ອນແຮງ'},
    {'emoji': '💯', 'label': 'ເຕັມຮ້ອຍ'},
    {'emoji': '💪', 'label': 'ກ້າມ'},
    {'emoji': '👏', 'label': 'ຕົບມື'},
    {'emoji': '🙏', 'label': 'ສາທຸ'},
    {'emoji': '🤝', 'label': 'ຈັບມື'},
    {'emoji': '🤞', 'label': 'ຂໍໂຊກ'},
    {'emoji': '✌️', 'label': 'ສັນຕິພາບ'},
    {'emoji': '🫶', 'label': 'ຮັກກັນ'},
    {'emoji': '👌', 'label': 'ໂອເຄ'},
    {'emoji': '👍', 'label': 'ມັກ'},
    {'emoji': '👎', 'label': 'ບໍ່ມັກ'},
    {'emoji': '🎉', 'label': 'ສະເຫຼີມສະຫຼອງ'},
    {'emoji': '🎊', 'label': 'ງານລ້ຽງ'},
    {'emoji': '🎈', 'label': 'ປູມເປົ້າ'},
    {'emoji': '🎁', 'label': 'ຂອງຂວັນ'},
    {'emoji': '💡', 'label': 'ໄອເດຍ'},
    {'emoji': '💸', 'label': 'ເງິນ'},
    {'emoji': '💰', 'label': 'ເງິນ'},
    {'emoji': '👑', 'label': 'ມົງກຸດ'},
    {'emoji': '🌈', 'label': 'ຮຸ້ງກິນນ້ຳ'},
    {'emoji': '☀️', 'label': 'ແດด'},
    {'emoji': '🌤️', 'label': 'ແດດ'},
    {'emoji': '⛅', 'label': 'ເມກ'},
    {'emoji': '🌧️', 'label': 'ຝົນ'},
    {'emoji': '⛈️', 'label': 'ພາຍຸ'},
    {'emoji': '❄️', 'label': 'ຫິມະ'},
    {'emoji': '☃️', 'label': 'ຕຸກຕາຫິມະ'},
    {'emoji': '🌊', 'label': 'ຄື້ນ'},
    {'emoji': '🎶', 'label': 'ດົນຕີ'},
    {'emoji': '🎵', 'label': 'ເພງ'},
    {'emoji': '🎤', 'label': 'ໄມຄ໌'},
    {'emoji': '🎧', 'label': 'ຫູຟັງ'},
    {'emoji': '🎸', 'label': 'ກີຕ້າ'},
    {'emoji': '🎹', 'label': 'ເປຍໂນ'},
    {'emoji': '🎺', 'label': 'ທຣັມເປັດ'},
    {'emoji': '🎻', 'label': 'ໄວໂອລິນ'},
    {'emoji': '🥁', 'label': 'ກອງ'},
    {'emoji': '⚽', 'label': 'ຟຸດບອນ'},
    {'emoji': '🏀', 'label': 'ບາສະເກັດບອນ'},
    {'emoji': '🏈', 'label': 'ຟຸດບອນ'},
    {'emoji': '⚾', 'label': 'ເບສບອນ'},
    {'emoji': '🎾', 'label': 'ເທັນນິສ'},
    {'emoji': '🏐', 'label': 'ວໍເລບອນ'},
    {'emoji': '🏉', 'label': 'ຮັກບີ້'},
    {'emoji': '🥏', 'label': 'ດິສກ໌'},
    {'emoji': '🎱', 'label': 'ບິນລຽດ'},
    {'emoji': '🪀', 'label': 'ໂຍໂຍ້'},
    {'emoji': '🪁', 'label': 'ວາວ'},
    {'emoji': '🎮', 'label': 'ເກມ'},
    {'emoji': '🕹️', 'label': 'ຈອຍສະຕິກ'},
    {'emoji': '🎲', 'label': 'ລูกເຕ່ົາ'},
    {'emoji': '♠️', 'label': 'ໂພດຳ'},
    {'emoji': '♥️', 'label': 'ໂພແດງ'},
    {'emoji': '♦️', 'label': 'ເຂົ້າຫຼາມຕັດ'},
    {'emoji': '♣️', 'label': 'ດອກຈິກ'},
    {'emoji': '🃏', 'label': 'ໂຈກເກີ'},
    {'emoji': '🎰', 'label': 'ສະລັອດ'},
    {'emoji': '🚗', 'label': 'ລົດຢົນ'},
    {'emoji': '🚕', 'label': 'ແທັກຊີ້'},
    {'emoji': '🚙', 'label': 'ລົດ'},
    {'emoji': '🚌', 'label': 'ລົດບັສ'},
    {'emoji': '🚎', 'label': 'ລົດລາງ'},
    {'emoji': '🏎️', 'label': 'ລົດແຂ່ງ'},
    {'emoji': '🚓', 'label': 'ຕຳຫຼວດ'},
    {'emoji': '🚒', 'label': 'ລົດດັບເພີງ'},
    {'emoji': '🚚', 'label': 'ລົດບັນທຸກ'},
    {'emoji': '🚀', 'label': 'ຈະຫຼວດ'},
    {'emoji': '✈️', 'label': 'ເຄື່ອງບິນ'},
    {'emoji': '🛸', 'label': 'ຈານບິນ'},
    {'emoji': '🚁', 'label': 'ເຮລິຄອບເຕີ'},
    {'emoji': '⛵', 'label': 'ເຮືອໃบ'},
    {'emoji': '🏠', 'label': 'ເຮືອນ'},
    {'emoji': '🏡', 'label': 'ເຮືອນ'},
    {'emoji': '🏢', 'label': 'ອາຄານ'},
    {'emoji': '🏣', 'label': 'ໄປສະນີ'},
    {'emoji': '🏥', 'label': 'ໂຮງໝໍ'},
    {'emoji': '🏦', 'label': 'ທະນາຄານ'},
    {'emoji': '🏨', 'label': 'ໂຮງແຮມ'},
    {'emoji': '🏩', 'label': 'ໂຮงແຮມ'},
    {'emoji': '🏪', 'label': 'ຮ້ານສະດວກຊື້'},
    {'emoji': '🏫', 'label': 'ໂຮງຮຽນ'},
    {'emoji': '🏬', 'label': 'ຫ້າງ'},
    {'emoji': '🏭', 'label': 'ໂຮງງານ'},
    {'emoji': '🏯', 'label': 'ປາສາດ'},
    {'emoji': '🏰', 'label': 'ປາສາດ'},
    {'emoji': '⛩️', 'label': 'ສານເຈົ້າ'},
    {'emoji': '🎪', 'label': 'ລະຄອນສັດ'},
    {'emoji': '🛍️', 'label': 'ຊັອບປິ້ງ'},
    {'emoji': '📱', 'label': 'ມືຖື'},
    {'emoji': '💻', 'label': 'ຄອมພິວເຕີ'},
    {'emoji': '⌨️', 'label': 'ຄີບອດ'},
    {'emoji': '🖥️', 'label': 'ຈໍຄອມ'},
    {'emoji': '🖨️', 'label': 'ເຄື່ອງພິມ'},
    {'emoji': '🎥', 'label': 'ກ້ອງວິດີໂອ'},
    {'emoji': '📷', 'label': 'ກ້ອງຖ່າຍຮູບ'},
    {'emoji': '📸', 'label': 'ກ້ອງຖ່າຍຮູບ'},
    {'emoji': '📹', 'label': 'ກ້ອງວິດີໂອ'},
    {'emoji': '💽', 'label': 'ແຜ່ນດິສก໌'},
    {'emoji': '💾', 'label': 'ຟລັອບປີດິສກ໌'},
    {'emoji': '💿', 'label': 'ຊີດີ'},
    {'emoji': '📀', 'label': 'ດີວີດີ'},
    {'emoji': '🧮', 'label': 'ລູກຄິດ'},
    {'emoji': '🎬', 'label': 'ຮູບເງົາ'},
  ];

  // ດຶງເອົາສະເພาະ 4 ອັນທຳອິດ
  static List<Map<String, String>> getFirstFour() {
    return allEmojis.take(4).toList();
  }

  // ຊອກຫາປ້າຍກຳກັບຈາກອີໂມຈິ
  static String getLabel(String emoji) {
    for (var item in allEmojis) {
      if (item['emoji'] == emoji) return item['label']!;
    }
    return '';
  }

  // ຄົ້ນຫາອີໂມຈິ
  static List<Map<String, String>> searchEmojis(String query) {
    if (query.isEmpty) return allEmojis;
    final q = query.toLowerCase();
    return allEmojis.where((item) {
      return item['emoji']!.contains(q) ||
          item['label']!.toLowerCase().contains(q);
    }).toList();
  }

  // ແບ່ງເປັນໜ້າໆ (paginate)
  static List<Map<String, String>> getPaginated(int page, int perPage) {
    final start = page * perPage;
    final end = (start + perPage).clamp(0, allEmojis.length);
    return allEmojis.sublist(start, end);
  }

  static int get totalEmojis => allEmojis.length;
}